Dev
UnfforU/LibraryWebAPI pull request #1
Opened 2023-10-02 16:48 UTC by UnfforU

Pull Request for LibraryWebAPI v1.0 

Create basic services and controllers.

2023-10-02 17:54 UTC, MaltsevaSoftline requested changes

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Controllers/LibraryController.cs
> +            return await _libraryService.GetAllLibraries();
If method is async it's a good practice to call it like GetAllLibrariesAsync. Good ref - linq methods

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Controllers/UserController.cs
> +        public async Task<List<User>> AddUser(UserDTO userDTO)
No IActionResult

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Models/Author.cs
> +    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
Do you need this property?

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Models/Book.cs
> +    public string Name { get; set; } = null!;
?

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Models/LibraryContext.cs
> +    public LibraryContext()
Do you need an empty constructor?

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Models/LibraryContext.cs
> +    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
Do you need this method?

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Models/LibraryContext.cs
> +                .HasMaxLength(50)
Name might be more than 50 chars

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Models/LibraryContext.cs
> +                .IsUnicode(false)
and your customer might be from China

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Models/LibraryContext.cs
> +            entity.HasIndex(e => e.AuthorId, "IXFK_book_author");
Do you need this property?

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Models/LibraryContext.cs
> +                .HasDefaultValue(new Guid())
Why do you use guid not just numbers as an id?

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Models/User.cs
> +    public bool? IsAdmin { get; set; }
What if we add another role? If many?

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Program.cs
> +builder.Services.Configure<AuthOptions>(builder.Configuration.GetSection("Auth"));
Cool, like this pattern

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Controllers/LibraryController.cs
> +        [HttpPut("{libraryId}")]
We may call this endpoint without admin role and without being authorized at all.

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Services/AuthService/AuthService.cs
> +                new Claim("isAdmin", user.IsAdmin == true ? "yes": "no")
What is we add a new role? If many?

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Services/BookService/BookService.cs
> +            };
Add mapper

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Services/BookService/BookService.cs
> +            _context.Entry(deletedBook).State = EntityState.Modified;
Why do you need this line?

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Services/BookService/BookService.cs
> +            throw new NotImplementedException();
?

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Services/LibraryService/LibraryService.cs
> +        {
Is it correct to return entity mode (not dto) to representation level?

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Services/UserService/UserService.cs
> +        private string ComputeSHA256(string input)
As for me it is auth service logics not user service

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Controllers/BookController.cs
> +            if (book != null)
If book (method parameter) not null?

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Controllers/LibraryController.cs
> +            return Ok(result);
You return NoContent when update book entity. It's not consistent to implement different behavior in practically similar situations

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Services/BookService/BookService.cs
> +            var author = _authorService.AddAuthor(new Author { AuthorId = Guid.NewGuid(), Name = book.AuthorName });
Each author has uniq id?

2023-10-02 17:54 UTC, MaltsevaSoftline commented on LibraryWebAPI/Services/BookService/BookService.cs
> +        public async Task<BookDTO?> UpdateBook(Guid bookId, BookDTO request)
BookDto request?

2023-10-10 07:27 UTC, TatsianaMaltseva requested changes

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/GlobalUsings.cs
> +global using LibraryWebAPI.Helpers;
I do not think all you application part should be aware of DB models (especially), or any other models, there are no namespaces on lines 13-17 that must be included if each other file

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/Helpers/CryptographyHelper.cs
> +        private const int MAXIMUM_SALT_LENGTH = 8;
Maximum? Your salt length may change?

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/Models/DB/Author.cs
> +    public Guid AuthorId { get; set; }
AuthorId inside Author entity

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/Models/DB/AuthorBook.cs
> +    public virtual Author Author { get; set; } = null!;
Do you use Author and Book property?

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/Models/DB/Book.cs
> +    public byte[]? Cover { get; set; }
Btw do you plan to store binaries in db?

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/Models/DB/WebLibraryDbContext.cs
> +                .HasConstraintName("FK_Author_Book_Author");
Do you need this line?

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/Models/DB/WebLibraryDbContext.cs
> +                .HasConstraintName("FK_Author_Book_Book");
and this

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/Models/DB/WebLibraryDbContext.cs
> +            entity.HasQueryFilter(library => EF.Property<bool>(library, "IsDeleted") == false);
What if you want to return deleted books also? Is this QueryFilter universal for possible cases regarding this project?

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/Models/DTO/UserDTO.cs
> +        public byte UserRole { get; set; }
Byte? Not enum?

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/Services/AuthorService/AuthorService.cs
> +            foreach (var a in _context.AuthorBooks.Where(ab => ab.AuthorId == author.AuthorId).ToList())
Is it possible to do without foreach? Like for ef do delete it on one's own?

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/Services/BookService/BookService.cs
> +            //Nedded cause i can't updBook by "= _mapper.Map()"
??

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/Services/UserService/UserService.cs
> +            if (IsUserExist(user.UserName))
UserName is uniq?

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/Services/UserService/UserService.cs
> +        public User? GetUserByLoginDTO(LoginDTO login)
In this metod in 2 of 3 cases you return null

2023-10-10 07:27 UTC, TatsianaMaltseva commented on LibraryWebAPI/Services/BookService/BookService.cs
> +                foreach (var a in _context.AuthorBooks.Where(ab => ab.BookId == book.BookId).ToList())
Use linq not foreach. Also, do you need to materializе the collection to change i?

2023-10-11 13:53 UTC, UnfforU commented on LibraryWebAPI/Models/DB/WebLibraryDbContext.cs
> +            entity.HasQueryFilter(library => EF.Property<bool>(library, "IsDeleted") == false);
In my own, I don't think, that it's good idea to get deleted objects by main controllers. 
Soft delete just get u opportunity to fast revert some accidental changes with t-sql, not with API server.

2023-10-11 14:18 UTC, UnfforU commented on LibraryWebAPI/Services/UserService/UserService.cs
> +            if (IsUserExist(user.UserName))
yes

2023-10-13 07:37 UTC, MaltsevaSoftline commented on LibraryWebAPI/Services/UserService/UserService.cs
> +            if (IsUserExist(user.UserName))
Ok

2023-10-13 07:37 UTC, MaltsevaSoftline approved these changes

2023-10-16 09:51 UTC, merged